### ISSUE TITLE
Implementar pantallas en front

### ISSUE THREAD

**Issue by ialberquilla** [Sassy-finance/sassy#2]
Implementar pantallas cuando se termine la #1 usando la plantilla https://github.com/bloomui/tokyo-free-white-nextjs-admin-dashboard

**Comment by ialberquilla** [comment]
Al hacer click en mortgage, se abrirá otra pantalla para conectarse al api de nordigen. 

Esto devuelve una lista de transacciones que se mostrarán en una pantalla como esta:

![image](https://user-images.githubusercontent.com/974720/225873603-e58aa04f-ddf2-471e-8af1-53a9af69deff.png)

El botón en vez de crear transaction, mostrará upload to Filecoin. Una vez subido se cambiará a Ask for claims

**Comment by ialberquilla** [comment]
Crear otra pantalla para que el usuario pueda consultar las claim offers que se han generado por validadores en sus datos. Otra entrada en el menu con el nombre

![image](https://user-images.githubusercontent.com/974720/225874736-656372a3-2153-4e2f-a54b-d23306a5c1bc.png)


Al hacer click ver las claims que ha solicitado, en forma de cards, y al hacer click en cada una mostrar una tabla con las offers que se han hecho sobre esos datos

**Comment by valentinnavalos** [comment]
PR: https://github.com/Sassy-finance/sassy/pull/20
