### ISSUE TITLE
Crear pantalla Mint NFT

### ISSUE THREAD

**Issue by ialberquilla** [Sassy-finance/sassy#29]
Crear una nueva pantalla donde el usuario podrá mintear un NFT con una claim válida.

Al hacer click en ella se mostrarán los Tier disponibles

![Image](https://user-images.githubusercontent.com/974720/226303875-f41d5415-3fab-441b-8321-c64b96c668bf.png)

El usuario validará la claim con el tier correspondiente y después tendrá un formulario para incluir los datos donde mintear el NFT

De momento dos campos:

Notional y rate

![Image](https://user-images.githubusercontent.com/974720/226304643-ab8d6844-5042-4460-a9b9-53be1052984b.png)

**Comment by valentinnavalos** [comment]
> No lo he puesto bien, pero falta añadir una entrada en el Menu para ir a esa pantalla "Your NFTs".
> 
> Lo de los tiers de las cards era solo para esta pantalla, se ha cambiado en todas.
> 
> No sé si hay form, pero no lo veo
> 
> @valentinnavalos

okk
